### ISSUE TITLE
Any plan to migrate the dashboard to Spring Boot Application?

### ISSUE THREAD

**Issue by linux-china** [vaadin/dashboard-demo#30]
Now most Java developer use Spring framework,  and Vaadin also supply spring boot starter. I wonder any plan to adopt spring boot for dashboard demo.

**Comment by fgianneschi** [comment]
Please don't do that. Lots of Java developers DON'T use Spring. You shouldn't introduce too many dependencies to other frameworks, because the main goal of this demo is to show the features and capabilities of Vaadin; additional technologies may only confuse beginners.

**Comment by elmot** [comment]
Actually we do not have any plans of that type. Spring is great, but I completely agree to @fgianneschi, there are lots of software systems without Spring, and the Dashboard is not going to be one more Spring-related example.
